### PR TITLE
fix NewClient

### PR DESCRIPTION
**Pull request by ramon15749**
# Summary

Please provide a summary of the change.

## Additional Information

Auxiliary information goes here.

## Test Plan

- Add information on how you tested your changes.

### CODE REVIEW

**Comment by tharusha-a** [comment]
**Do it run tho**

**Comment by ramon15749** [comment]
> **Do it run tho**

oi you **literally** told what to type. i _trusted_ you

**Comment by tharusha-a** [comment]
> > **Do it run tho**
> 
> oi you **literally** told what to type. i _trusted_ you

This is a conspiracy

**Review by tharusha-a — APPROVED** [review]
Seems aight

**Pull request merged**
